encyclopedia/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.showEntry, name="showEntry"),
    path("search/", views.search, name="search"),
    path("newPage/", views.newPage, name="newPage"),
    path("saveNewEntry/", views.saveNewEntry, name="saveNewEntry"),
    path("editEntry/<str:name>", views.editEntry, name="editEntry"),
    path("saveEdit/<str:name>", views.saveEdit, name="saveEdit"),
    path("randomPage/", views.randomPage, name="randomPage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from http.client import HTTPResponse
from django import forms
from django.shortcuts import render, redirect
import random
from markdown2 import Markdown

from . import util

class NewForm(forms.Form):
    title = forms.CharField(label='Title and Content:', max_length=100, widget=forms.TextInput(attrs={
        'name': 'title', 'class': 'title'
    }))
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'name': 'content', 'class': 'content'
    }))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def showEntry(request, name):
    name = name.lower()

    if name == "css" or name == "html" or name == "cs50":
        name = name.upper()
    else:
        name = name.title()

    if name not in util.list_entries():
        return render(request, "encyclopedia/entryNotFound.html", {
            "name": name
        })

    return render(request, "encyclopedia/showEntry.html", {
        "entry": Markdown().convert(util.get_entry(name)), "name": name
    })

def search(request):
    matchingEntries = []
    name = request.GET.get("q", "")
    name = name.lower()

    # check multiple conditions to format correctly
    if name == "css" or name == "html" or name == "cs50":
        name = name.upper()
    else:
        name = name.title()

    # check every entry in database for match
    for entry in util.list_entries():
        # if there is an exact match then go to entry page
        if entry == name:
            return redirect('encyclopedia:showEntry', name)
        
        # if there is a partial match then add to matching list
        if name.lower() in entry.lower():
            matchingEntries.append(entry)
    
    # if there are no matches, then go to entry not found page
    if not matchingEntries:
        return render(request, "encyclopedia/entryNotFound.html", {
            "name": name
        })
    else:
        # else go to search results page and display list of matching entries
        return render(request, "encyclopedia/searchResults.html", {
            "name": name, "matchingEntries": matchingEntries
        })

def newPage(request):
    form = NewForm()

    return render(request, "encyclopedia/newPage.html", {
        "form": form
    })

def saveNewEntry(request):
    # get title
    newEntryTitle = request.POST.get("title", "")

    match = False
    # check if title already exists in list of entries
    for entry in util.list_entries():
        if newEntryTitle.lower() == entry.lower():
            match = True
            break

    # if there was a match, then go to error page
    if match:
        return render(request, "encyclopedia/entryExistsError.html", {
            "name": newEntryTitle
        })
    else:
        # else if no match then continue to saving entry
        # get content
        newEntryContent = request.POST.get("content", "")

        util.save_entry(newEntryTitle, newEntryContent)
        
        return redirect("encyclopedia:showEntry", newEntryTitle)

def editEntry(request, name):
    # get entry first
    entry = Markdown().convert(util.get_entry(name))

    # go to edit entry page
    return render(request, "encyclopedia/editPage.html", {
        "name": name, "entry": entry
    })

def saveEdit(request, name):
    # get edited content
    content = request.POST.get("content", "")

    # save content
    util.save_entry(name, content)

    # show page with edit
    return redirect("encyclopedia:showEntry", name)

def randomPage(request):
    # use choice function to get random entry to display
    entry = random.choice(util.list_entries())

    # redirect to show entry
    return redirect("encyclopedia:showEntry", entry)

encyclopedia/templates/encyclopedia/editPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}

    <h1>Edit Page '{{ name }}':</h1>
    <div class="row">
        <div class="bodyNew col-lg-10 col-md-10">
            <form action="{% url 'encyclopedia:saveEdit' name %}" method="POST">
                {% csrf_token %}
                <textarea id="content" name="content">{{ entry | safe }}</textarea>
                <input type="submit" value="Save Edit">
            </form>
        </div>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/entryExistsError.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    ERROR
{% endblock %}

{% block body %}
    <h1>ERROR: '{{ name }}' already exists</h1>
    <p>The entry '{{ name }}' already exists. You may view it by clicking <a href="{% url 'encyclopedia:showEntry' name %}">here</a></p>
{% endblock %}

encyclopedia/templates/encyclopedia/entryNotFound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    ERROR
{% endblock %}

{% block body %}
    <h1>ERROR: '{{ name }}' not found</h1>
    <p>The entry '{{ name }}' does not exist yet. You may wish to create it by clicking <a href="{% url 'encyclopedia:newPage' %}">here</a></p>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:showEntry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}

    <h1>Create New Page</h1>
    <div class="row">
        <div class="bodyNew col-lg-10 col-md-10">
            <form action="{% url 'encyclopedia:saveNewEntry' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit Entry">
            </form>
        </div>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/searchResults.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>Search results for {{ name }}:</h1>

    <ul>
        {% for entry in matchingEntries %}
            <li><a href="{% url 'encyclopedia:showEntry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/showEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ name }}
{% endblock %}

{% block body %}

    {{ entry | safe }}

    <div class="editLink">
        <a href="{% url 'encyclopedia:editEntry' name %}">Edit Entry</a>
    </div>

{% endblock %}